//! Built-in macro definitions — full catalog.
//!
//! Contains the canonical list of all SugarCube 2 builtin macro definitions,
//! organized by category (Control flow, Variables, Output, DOM, Links, etc.).

use crate::types::{MacroArgDef, MacroArgKind, MacroCategory, MacroDef};

/// The full list of SugarCube builtin macro definitions.
///
/// Contains ~50+ macro definitions covering control flow, variables, output,
/// DOM manipulation, links, forms, navigation, timing, widgets, audio, and
/// deprecated macros.
pub fn builtin_macros() -> &'static [MacroDef] {
    use MacroArgKind::*;

    static BUILTINS: &[MacroDef] = &[
        // ── Control flow ─────────────────────────────────────────────────────
        MacroDef {
            name: "if",
            description: "Conditional block. `<<if $condition>>…<</if>>`",
            has_body: true,
            args: None,
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Control,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "elseif",
            description: "Else-if branch within `<<if>>`.",
            has_body: false,
            args: None,
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Control,
            container: None,
            container_any_of: Some(&["if", "elseif"]),
        },
        MacroDef {
            name: "else",
            description: "Else branch within `<<if>>`.",
            has_body: false,
            args: None,
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Control,
            container: Some("if"),
            container_any_of: None,
        },
        MacroDef {
            name: "for",
            description: "Iteration. `<<for _i, $arr>>…<</for>>`",
            has_body: true,
            args: None,
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Control,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "break",
            description: "Break out of the nearest enclosing `<<for>>` loop.",
            has_body: false,
            args: None,
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Control,
            container: Some("for"),
            container_any_of: None,
        },
        MacroDef {
            name: "continue",
            description: "Skip to the next iteration of the nearest `<<for>>` loop.",
            has_body: false,
            args: None,
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Control,
            container: Some("for"),
            container_any_of: None,
        },
        MacroDef {
            name: "switch",
            description: "Switch on an expression. `<<switch $v>><<case 1>>…<</switch>>`",
            has_body: true,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "expression",
                is_passage_ref: false,
                is_selector: false,
                is_variable: false,
                is_required: true,
                kind: Expression,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Control,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "case",
            description: "Case arm within `<<switch>>`.",
            has_body: false,
            args: None,
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Control,
            container: Some("switch"),
            container_any_of: None,
        },
        MacroDef {
            name: "default",
            description: "Default arm within `<<switch>>`.",
            has_body: false,
            args: None,
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Control,
            container: Some("switch"),
            container_any_of: None,
        },

        // ── Variables ─────────────────────────────────────────────────────────
        MacroDef {
            name: "set",
            description: "Assign a value: `<<set $var to expression>>`",
            has_body: false,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "expression",
                is_passage_ref: false,
                is_selector: false,
                is_variable: false,
                is_required: false,
                kind: Expression,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Variables,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "unset",
            description: "Remove a story variable: `<<unset $var>>`",
            has_body: false,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "variable",
                is_passage_ref: false,
                is_selector: false,
                is_variable: true,
                is_required: true,
                kind: Variable,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Variables,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "capture",
            description: "Capture variables for use in closures.",
            has_body: true,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "variable",
                is_passage_ref: false,
                is_selector: false,
                is_variable: true,
                is_required: true,
                kind: Variable,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Variables,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "run",
            description: "Execute an expression without producing output: `<<run $arr.push(\"item\")>>`",
            has_body: false,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "expression",
                is_passage_ref: false,
                is_selector: false,
                is_variable: false,
                is_required: false,
                kind: Expression,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Variables,
            container: None,
            container_any_of: None,
        },

        // ── Output ────────────────────────────────────────────────────────────
        MacroDef {
            name: "print",
            description: "Print the result of an expression.",
            has_body: false,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "expression",
                is_passage_ref: false,
                is_selector: false,
                is_variable: false,
                is_required: true,
                kind: Expression,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Output,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "=",
            description: "Short alias for `<<print>>`.",
            has_body: false,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "expression",
                is_passage_ref: false,
                is_selector: false,
                is_variable: false,
                is_required: true,
                kind: Expression,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Output,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "-",
            description: "Print without leading/trailing whitespace.",
            has_body: false,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "expression",
                is_passage_ref: false,
                is_selector: false,
                is_variable: false,
                is_required: true,
                kind: Expression,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Output,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "type",
            description: "Typewriter effect: displays text character by character.",
            has_body: true,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "speed",
                is_passage_ref: false,
                is_selector: false,
                is_variable: false,
                is_required: true,
                kind: String,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Output,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "nobr",
            description: "Remove line breaks from enclosed content.",
            has_body: true,
            args: None,
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Output,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "silently",
            description: "Execute enclosed code without producing output.",
            has_body: true,
            args: None,
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Output,
            container: None,
            container_any_of: None,
        },

        // ── DOM / Display ─────────────────────────────────────────────────────
        MacroDef {
            name: "append",
            description: "Append content to a selector: `<<append \"#id\">>…<</append>>`",
            has_body: true,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "selector",
                is_passage_ref: false,
                is_selector: true,
                is_variable: false,
                is_required: true,
                kind: Selector,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Dom,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "prepend",
            description: "Prepend content to a selector.",
            has_body: true,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "selector",
                is_passage_ref: false,
                is_selector: true,
                is_variable: false,
                is_required: true,
                kind: Selector,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Dom,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "replace",
            description: "Replace element content.",
            has_body: true,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "selector",
                is_passage_ref: false,
                is_selector: true,
                is_variable: false,
                is_required: true,
                kind: Selector,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Dom,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "remove",
            description: "Remove matching element(s) from the DOM.",
            has_body: false,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "selector",
                is_passage_ref: false,
                is_selector: true,
                is_variable: false,
                is_required: true,
                kind: Selector,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Dom,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "copy",
            description: "Copy existing element content into another.",
            has_body: true,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "selector",
                is_passage_ref: false,
                is_selector: true,
                is_variable: false,
                is_required: true,
                kind: Selector,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Dom,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "addclass",
            description: "Add CSS class(es) to element(s).",
            has_body: false,
            args: Some(&[
                MacroArgDef {
                    position: 0,
                    label: "selector",
                    is_passage_ref: false,
                    is_selector: true,
                    is_variable: false,
                    is_required: true,
                    kind: Selector,
                },
                MacroArgDef {
                    position: 1,
                    label: "class",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: false,
                    is_required: true,
                    kind: String,
                },
            ]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Dom,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "removeclass",
            description: "Remove CSS class(es) from element(s).",
            has_body: false,
            args: Some(&[
                MacroArgDef {
                    position: 0,
                    label: "selector",
                    is_passage_ref: false,
                    is_selector: true,
                    is_variable: false,
                    is_required: true,
                    kind: Selector,
                },
                MacroArgDef {
                    position: 1,
                    label: "class",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: false,
                    is_required: true,
                    kind: String,
                },
            ]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Dom,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "toggleclass",
            description: "Toggle CSS class(es) on element(s).",
            has_body: false,
            args: Some(&[
                MacroArgDef {
                    position: 0,
                    label: "selector",
                    is_passage_ref: false,
                    is_selector: true,
                    is_variable: false,
                    is_required: true,
                    kind: Selector,
                },
                MacroArgDef {
                    position: 1,
                    label: "class",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: false,
                    is_required: true,
                    kind: String,
                },
            ]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Dom,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "css",
            description: "Inject inline CSS into the page.",
            has_body: true,
            args: None,
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Dom,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "script",
            description: "Execute JavaScript: `<<script>>…<</script>>`",
            has_body: true,
            args: None,
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Dom,
            container: None,
            container_any_of: None,
        },

        // ── Links / Interaction ───────────────────────────────────────────────
        MacroDef {
            name: "link",
            description: "Inline link with click handler: `<<link \"label\" \"passage\">>…<</link>>`",
            has_body: true,
            args: Some(&[
                MacroArgDef {
                    position: 0,
                    label: "label",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: false,
                    is_required: true,
                    kind: String,
                },
                MacroArgDef {
                    position: 1,
                    label: "passage",
                    is_passage_ref: true,
                    is_selector: false,
                    is_variable: false,
                    is_required: false,
                    kind: String,
                },
            ]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Links,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "button",
            description: "Button with click handler: `<<button \"label\" \"passage\">>…<</button>>`",
            has_body: true,
            args: Some(&[
                MacroArgDef {
                    position: 0,
                    label: "label",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: false,
                    is_required: true,
                    kind: String,
                },
                MacroArgDef {
                    position: 1,
                    label: "passage",
                    is_passage_ref: true,
                    is_selector: false,
                    is_variable: false,
                    is_required: false,
                    kind: String,
                },
            ]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Links,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "linkappend",
            description: "Link that appends content when clicked: `<<linkappend \"label\">>…<</linkappend>>`",
            has_body: true,
            args: Some(&[
                MacroArgDef {
                    position: 0,
                    label: "label",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: false,
                    is_required: true,
                    kind: String,
                },
                MacroArgDef {
                    position: 1,
                    label: "passage",
                    is_passage_ref: true,
                    is_selector: false,
                    is_variable: false,
                    is_required: false,
                    kind: String,
                },
            ]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Links,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "linkprepend",
            description: "Link that prepends content when clicked: `<<linkprepend \"label\">>…<</linkprepend>>`",
            has_body: true,
            args: Some(&[
                MacroArgDef {
                    position: 0,
                    label: "label",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: false,
                    is_required: true,
                    kind: String,
                },
                MacroArgDef {
                    position: 1,
                    label: "passage",
                    is_passage_ref: true,
                    is_selector: false,
                    is_variable: false,
                    is_required: false,
                    kind: String,
                },
            ]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Links,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "linkreplace",
            description: "Link that replaces itself with content when clicked: `<<linkreplace \"label\">>…<</linkreplace>>`",
            has_body: true,
            args: Some(&[
                MacroArgDef {
                    position: 0,
                    label: "label",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: false,
                    is_required: true,
                    kind: String,
                },
                MacroArgDef {
                    position: 1,
                    label: "passage",
                    is_passage_ref: true,
                    is_selector: false,
                    is_variable: false,
                    is_required: false,
                    kind: String,
                },
            ]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Links,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "actions",
            description: "Shorthand for a group of one-shot passage links.",
            has_body: true,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "passage",
                is_passage_ref: true,
                is_selector: false,
                is_variable: false,
                is_required: true,
                kind: String,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Links,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "click",
            description: "Alias for `<<link>>` (deprecated; prefer `<<link>>`).",
            has_body: true,
            args: Some(&[
                MacroArgDef {
                    position: 0,
                    label: "label",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: false,
                    is_required: true,
                    kind: String,
                },
                MacroArgDef {
                    position: 1,
                    label: "passage",
                    is_passage_ref: true,
                    is_selector: false,
                    is_variable: false,
                    is_required: false,
                    kind: String,
                },
            ]),
            deprecated: true,
            deprecation_message: Some("<<click>> is deprecated. Use <<link>> instead."),
            category: MacroCategory::Links,
            container: None,
            container_any_of: None,
        },

        // ── Forms ─────────────────────────────────────────────────────────────
        MacroDef {
            name: "checkbox",
            description: "Bind a checkbox to a story variable.",
            has_body: false,
            args: Some(&[
                MacroArgDef {
                    position: 0,
                    label: "label",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: false,
                    is_required: false,
                    kind: String,
                },
                MacroArgDef {
                    position: 1,
                    label: "variable",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: true,
                    is_required: false,
                    kind: Variable,
                },
                MacroArgDef {
                    position: 2,
                    label: "checked",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: false,
                    is_required: false,
                    kind: String,
                },
                MacroArgDef {
                    position: 3,
                    label: "unchecked",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: false,
                    is_required: false,
                    kind: String,
                },
            ]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Forms,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "radiobutton",
            description: "Bind a radio button to a story variable.",
            has_body: false,
            args: Some(&[
                MacroArgDef {
                    position: 0,
                    label: "label",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: false,
                    is_required: false,
                    kind: String,
                },
                MacroArgDef {
                    position: 1,
                    label: "variable",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: true,
                    is_required: false,
                    kind: Variable,
                },
                MacroArgDef {
                    position: 2,
                    label: "value",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: false,
                    is_required: false,
                    kind: String,
                },
            ]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Forms,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "textarea",
            description: "Bind a `<textarea>` to a story variable.",
            has_body: false,
            args: Some(&[
                MacroArgDef {
                    position: 0,
                    label: "variable",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: true,
                    is_required: true,
                    kind: Variable,
                },
                MacroArgDef {
                    position: 1,
                    label: "placeholder",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: false,
                    is_required: false,
                    kind: String,
                },
            ]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Forms,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "textbox",
            description: "Bind a text input to a story variable.",
            has_body: false,
            args: Some(&[
                MacroArgDef {
                    position: 0,
                    label: "variable",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: true,
                    is_required: true,
                    kind: Variable,
                },
                MacroArgDef {
                    position: 1,
                    label: "placeholder",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: false,
                    is_required: false,
                    kind: String,
                },
            ]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Forms,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "numberbox",
            description: "Bind a numeric input to a story variable.",
            has_body: false,
            args: Some(&[
                MacroArgDef {
                    position: 0,
                    label: "variable",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: true,
                    is_required: true,
                    kind: Variable,
                },
                MacroArgDef {
                    position: 1,
                    label: "default",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: false,
                    is_required: false,
                    kind: Expression,
                },
            ]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Forms,
            container: None,
            container_any_of: None,
        },

        // ── Navigation ────────────────────────────────────────────────────────
        MacroDef {
            name: "goto",
            description: "Navigate to a passage: `<<goto \"passage\">>`",
            has_body: false,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "passage",
                is_passage_ref: true,
                is_selector: false,
                is_variable: false,
                is_required: true,
                kind: String,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Navigation,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "back",
            description: "Return to the previous passage, optionally a specific one.",
            has_body: false,
            args: Some(&[
                MacroArgDef {
                    position: 0,
                    label: "display_text",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: false,
                    is_required: false,
                    kind: String,
                },
                MacroArgDef {
                    position: 1,
                    label: "passage",
                    is_passage_ref: true,
                    is_selector: false,
                    is_variable: false,
                    is_required: false,
                    kind: String,
                },
            ]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Navigation,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "return",
            description: "Navigate using browser history, optionally to a specific passage.",
            has_body: false,
            args: Some(&[
                MacroArgDef {
                    position: 0,
                    label: "display_text",
                    is_passage_ref: false,
                    is_selector: false,
                    is_variable: false,
                    is_required: false,
                    kind: String,
                },
                MacroArgDef {
                    position: 1,
                    label: "passage",
                    is_passage_ref: true,
                    is_selector: false,
                    is_variable: false,
                    is_required: false,
                    kind: String,
                },
            ]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Navigation,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "include",
            description: "Include and render another passage inline: `<<include \"passage\">>`",
            has_body: false,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "passage",
                is_passage_ref: true,
                is_selector: false,
                is_variable: false,
                is_required: true,
                kind: String,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Navigation,
            container: None,
            container_any_of: None,
        },

        // ── Timing ────────────────────────────────────────────────────────────
        MacroDef {
            name: "timed",
            description: "Display content after a delay: `<<timed 2s>>…<</timed>>`",
            has_body: true,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "delay",
                is_passage_ref: false,
                is_selector: false,
                is_variable: false,
                is_required: true,
                kind: String,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Timing,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "repeat",
            description: "Repeat content on an interval.",
            has_body: true,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "interval",
                is_passage_ref: false,
                is_selector: false,
                is_variable: false,
                is_required: true,
                kind: String,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Timing,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "stop",
            description: "Stop the nearest `<<timed>>` or `<<repeat>>`.",
            has_body: false,
            args: None,
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Timing,
            container: None,
            container_any_of: Some(&["timed", "repeat"]),
        },

        // ── Widgets / Audio ───────────────────────────────────────────────────
        MacroDef {
            name: "widget",
            description: "Define a reusable custom macro.",
            has_body: true,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "name",
                is_passage_ref: false,
                is_selector: false,
                is_variable: false,
                is_required: true,
                kind: String,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Widgets,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "done",
            description: "Execute code after the passage is fully rendered.",
            has_body: true,
            args: None,
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Output,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "audio",
            description: "Control audio: `<<audio \"id\" play>>`",
            has_body: false,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "id",
                is_passage_ref: false,
                is_selector: false,
                is_variable: false,
                is_required: true,
                kind: String,
            }]),
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Audio,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "playlist",
            description: "Control an audio playlist.",
            has_body: false,
            args: None,
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Audio,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "masteraudio",
            description: "Control the master audio.",
            has_body: false,
            args: None,
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Audio,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "createplaylist",
            description: "Define a new audio playlist.",
            has_body: true,
            args: None,
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Audio,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "cacheaudio",
            description: "Cache an audio track.",
            has_body: false,
            args: None,
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Audio,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "waitforaudio",
            description: "Pause rendering until cached audio is ready.",
            has_body: false,
            args: None,
            deprecated: false,
            deprecation_message: None,
            category: MacroCategory::Audio,
            container: None,
            container_any_of: None,
        },

        // ── Deprecated macros ─────────────────────────────────────────────────
        MacroDef {
            name: "display",
            description: "Deprecated — use `<<include>>` instead.",
            has_body: false,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "passageName",
                is_passage_ref: true,
                is_selector: false,
                is_variable: false,
                is_required: true,
                kind: String,
            }]),
            deprecated: true,
            deprecation_message: Some("<<display>> is deprecated. Use <<include>> instead."),
            category: MacroCategory::Navigation,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "remember",
            description: "Deprecated in SugarCube 2 — use `<<set>>` with persistent storage instead.",
            has_body: false,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "$var to expr",
                is_passage_ref: false,
                is_selector: false,
                is_variable: false,
                is_required: false,
                kind: Expression,
            }]),
            deprecated: true,
            deprecation_message: Some("<<remember>> is deprecated. Use <<set>> with persistent storage instead."),
            category: MacroCategory::Variables,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "forget",
            description: "Deprecated in SugarCube 2 — use `<<set>>` with persistent storage instead.",
            has_body: false,
            args: Some(&[MacroArgDef {
                position: 0,
                label: "$var",
                is_passage_ref: false,
                is_selector: false,
                is_variable: true,
                is_required: true,
                kind: Variable,
            }]),
            deprecated: true,
            deprecation_message: Some("<<forget>> is deprecated. Use <<set>> with persistent storage instead."),
            category: MacroCategory::Variables,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "setcss",
            description: "Deprecated — use `<<addclass>>` or `<<removeclass>>` instead.",
            has_body: false,
            args: None,
            deprecated: true,
            deprecation_message: Some("<<setcss>> is deprecated. Use <<addclass>> or <<removeclass>> instead."),
            category: MacroCategory::Dom,
            container: None,
            container_any_of: None,
        },
        MacroDef {
            name: "settitle",
            description: "Deprecated — set `document.title` directly via `<<run>>` instead.",
            has_body: false,
            args: None,
            deprecated: true,
            deprecation_message: Some("<<settitle>> is deprecated. Set document.title directly via <<run>> instead."),
            category: MacroCategory::Dom,
            container: None,
            container_any_of: None,
        },
    ];

    BUILTINS
}
