/**
 * Knot v2 — Harlowe 3 Runtime Globals & Virtual Prelude
 *
 * Harlowe exposes several runtime objects that authors can reference
 * in their stories. This module defines them for completion, hover,
 * and diagnostic support.
 *
 * Key Harlowe runtime globals:
 *   - passage       — the current passage object
 *   - passages      — a datamap of all passages
 *   - history       — navigation history array
 *   - ?hookName     — hook references (syntax handled by lexer)
 *   - (macro:)      — custom macro definition (handled by customMacros capability)
 */

import type { RuntimeGlobalDef } from '../_types';

// ═══════════════════════════════════════════════════════════════════
// RUNTIME GLOBALS
// ═══════════════════════════════════════════════════════════════════

export const RUNTIME_GLOBALS: readonly RuntimeGlobalDef[] = [
  {
    name: 'passage',
    description: 'The current passage object. Has "name" and "source" properties.',
    hasMembers: true,
    members: [
      { name: 'name', description: 'The name of the current passage', type: 'string' },
      { name: 'source', description: 'The source text of the current passage', type: 'string' },
      { name: 'tags', description: 'An array of the current passage\'s tags', type: 'array' },
    ],
  },
  {
    name: 'passages',
    description: 'A datamap containing all passages, keyed by passage name.',
    hasMembers: true,
    members: [
      { name: 'name', description: 'Access a passage by name', type: 'datamap' },
    ],
  },
  {
    name: 'history',
    description: 'An array of passage names representing the navigation history.',
    hasMembers: true,
    members: [
      { name: 'length', description: 'Number of entries in the history', type: 'number' },
    ],
  },
];

// ═══════════════════════════════════════════════════════════════════
// VIRTUAL RUNTIME PRELUDE
// ═══════════════════════════════════════════════════════════════════

/**
 * Virtual prelude for Harlowe analysis.
 * Declares the runtime globals so the JS/CSS analyzer can recognize them.
 */
export const VIRTUAL_RUNTIME_PRELUDE = `// Harlowe 3 Virtual Runtime Prelude
// Auto-generated by Knot LSP — do not edit

var passage = {
  name: "",
  source: "",
  tags: []
};

var passages = {};

var history = [];
`;
